RECOVERY_VARIANT := twrp

# RECOVERY
BOARD_HAS_DOWNLOAD_MODE := true
TARGET_RECOVERY_PIXEL_FORMAT := "ABGR_8888"
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery/root/system/etc/recovery.fstab

PLATFORM_SECURITY_PATCH := 2021-03-01

# TWRP
TW_INCLUDE_CRYPTO := false
TW_NO_REBOOT_BOOTLOADER := true
TW_HAS_DOWNLOAD_MODE := true
RECOVERY_SDCARD_ON_DATA := true
TW_NO_LEGACY_PROPS := true
TW_NO_HAPTICS := true
TW_USE_NEW_MINADBD := true
TW_EXCLUDE_TWRPAPP := true
TW_USE_TOOLBOX := true

THEME_NAME := stock
TW_CUSTOM_THEME := $(DEVICE_PATH)/theme/$(THEME_NAME)
TW_DEVICE_VERSION := 1_nubianprince

# init.recovery.usb.rc
TW_EXCLUDE_DEFAULT_USB_INIT := true
